# Generated by Django 5.0.1 on 2024-01-18 13:02

import django.db.models.deletion
import django.utils.timezone
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='category', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=100)),
                ('enterprise', models.CharField(help_text='enterprise', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=100)),
                ('department', models.CharField(help_text='department', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to=portfolio.models.upload_to_portfolio_thumbnail)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('personal_visible', models.CharField(choices=[('private', 'blind'), ('friend', 'friend'), ('public', 'open')], max_length=10)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='portfolio.category')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enterprise', models.CharField(help_text='enterprise', max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_visible', to='portfolio.user')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='portfolio.user'),
        ),
    ]
