# Generated by Django 5.0.1 on 2024-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='thumbnail',
            field=models.CharField(max_length=10000),
        ),
    ]
