# Generated by Django 5.0.1 on 2024-02-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_thumbnail_portfolio_thumbnail_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise',
            field=models.CharField(help_text='enterprise', max_length=100, unique=True),
        ),
    ]
