# Generated by Django 5.0.1 on 2024-02-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_enterprise_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise',
            field=models.CharField(help_text='enterprise', max_length=100),
        ),
    ]
