# Generated by Django 5.0.1 on 2024-02-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
