# Generated by Django 5.0.1 on 2024-02-08 23:53

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_enterprise_enterprise_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='enterprise_code',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='deadline',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
